
################################################################################################################ 
########### LED MANAGER NODE
################################################################################################################

/move_base/led_manager:
  ros__parameters:
    
    # Colors index for the led strip
    black: 200                #000000
    blue: 1                   #0000ff
    cyan: 2                   #00A8FF
    green: 3                  #00ff00
    light_green: 100          #00fa9a
    orange: 6                 #ffa500
    pink: 4                   #ff0084
    purple: 7                 #800080
    red: 2                    #ff0000
    yellow: 5                 #ffff00
    white: 0                  #ffffff
    
    # Index for ghost and waypoints goals 
    ghost_goal: 1
    waypoint_goal: 0

    # Debug / test
    use_sim_time: false     # Use simulation test
    debug: false            # Enable debug prints 
    unit_test: true        # Allow the node runs isolated 



################################################################################################################ 
########### SAFE TWIST
################################################################################################################

/move_base/safe_twist:
  ros__parameters:

    # Ultrasonic sensors 
    disable_ultrasonics: true
    safe_distance: 100.0              # Stopping distance when detecting an object 

    # Velocity limits 
    max_angular_speed: 20.0           
    max_linear_speed: 2.5
    motor_brake_factor: -1

    # Debug / test
    use_sim_time: false               # Use simulation test
    debug: false                      # Enable debug prints


################################################################################################################ 
########### JOY ESP INTERFACE
################################################################################################################

/move_base/joy_esp_interface:
  ros__parameters:

    # Joystick limits 
    drift_analog_tolerance: 20
    max_value_controller: 127
    
    # Velocity limits 
    max_vel_joy_angular: 10.0
    max_vel_joy_linear: 5.0
    
    # Debug / test
    use_sim_time: false     # Use simulation test
    debug: false            # Enable debug prints 
    unit_test: true        # Allow the node runs isolated  



################################################################################################################ 
########### ODOMETRY
################################################################################################################

/move_base/odometry:
  ros__parameters:

    # Robots dimensions
    base_link_offset: 0.08
    wheels_radius: 0.075
    wheels_track: 0.38
    
    # Enconder config 
    ticks_per_revolution: 7200
    
    # Debug / test
    use_sim_time: false     # Use simulation test
    debug: false            # Enable debug prints 

  
