
################################################################################################################ 
########### LED MANAGER NODE
################################################################################################################

led_manager:
  WHITE: 0
  BLUE: 5
  YELLOW: 5
  PINK: 4
  GREEN: 3
  ORANGE: 6
  RED: 2
  BLACK: -1

  WAYPOINT_GOAL: 0  # Goals points that the robot must signal
  GHOST_GOAL: 1


################################################################################################################ 
########### SAFE TWIST
################################################################################################################

safe_twist: 
  safe_distance: 100    # distance in cm 
 
  motor_brake_factor: -1 
 
  max_linear_speed: 2.0  
  max_angular_speed: 20.0




################################################################################################################ 
########### JOY ESP INTERFACE
################################################################################################################

joy_esp_interface: 
  MAX_SPEED_JOY_LINEAR: 5
  MAX_SPEED_JOY_ANGULAR: 10
  
  MAX_VALUE_CONTROLLER: 127
  
  DRIFT_ANALOG_TOLERANCE: 20




################################################################################################################ 
########### ODOMETRY
################################################################################################################

odometry:
  wheels_track: 0.3800  # distance in meters 
  wheels_radius: 0.075  # distance in meters 
  ticks_per_revolution: 7200 # 2400 * 3
  base_link_offset: 0.08 # distance (in meters) between the base_footprint and base_link 


  
