led_manager:
  WHITE: 0
  BLUE: 5
  YELLOW: 5
  PINK: 4
  GREEN: 3
  ORANGE: 6
  RED: 2
  BLACK: -1

  WAYPOINT_GOAL: 0  # Goals points that the robot must signal
  GHOST_GOAL: 1


safe_twist: 
  SAFE_DISTANCE: 100    # distance in cm
 
  MOTOR_BRAKE_FACTOR: -1
 
  MAX_LINEAR_SPEED: 2
  MAX_ANGULAR_SPEED: 20


joy_esp_interface: 
  MAX_SPEED_ROBOT_LINEAR: 5
  MAX_SPEED_ROBOT_ANGULAR: 10
  
  MAX_VALUE_CONTROLER: 127
  
  DRIFT_ANALOG_TOLERANCE: 20


odometry:
  wheels_track: 0.3800  # distance in meters 
  wheels_radius: 0.075  # distance in meters 
  ticks_per_revolution: 7200 # 2400 * 3
  base_link_offset: 0.08 # distance (in meters) between the base_footprint and base_link 


  
